// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Ca struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Yaml      string `json:"yaml"`
}

type CreateCAInput struct {
	Yaml string `json:"yaml"`
}

type CreateOrdererInput struct {
	Yaml string `json:"yaml"`
}

type CreatePeerInput struct {
	Yaml string `json:"yaml"`
}

type NameAndNamespace struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type Namespace struct {
	Name string `json:"name"`
}

type Orderer struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Yaml      string `json:"yaml"`
}

type Peer struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Yaml      string `json:"yaml"`
}

type UpdateeCAInput struct {
	Yaml *string `json:"yaml"`
}

type UpdateeOrdererInput struct {
	Yaml *string `json:"yaml"`
}

type UpdateePeerInput struct {
	Yaml *string `json:"yaml"`
}
