projects:
  hlf-operator-api:
    schema: http://localhost:8003/graphql
    documents: src/operations/**/*.graphql
    extensions:
      endpoints:
        default:
          url: http://localhost:8003/graphql
