schema:
  - ./schemas/**/*.graphql

resolver:
  filename: gql/resolvers/resolvers.go
  package: resolvers
  type: Resolver
exec:
  filename: gql/generated.go
  package: gql
model:
  filename: gql/models/models.go
  package: models

models:
  Channel:
    model: github.com/kfsoftware/hlf-operator-ui/api/gql/models.Channel
  Peer:
    model: github.com/kfsoftware/hlf-operator-ui/api/gql/models.Peer
  Orderer:
    model: github.com/kfsoftware/hlf-operator-ui/api/gql/models.Orderer
  CA:
    model: github.com/kfsoftware/hlf-operator-ui/api/gql/models.Ca

