name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./ui

      - name: Build project
        run: npm run build
        working-directory: ./ui

      - name: Copy build to api
        run: cp -r ./ui/dist ./api/web
        working-directory: .

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
          workdir: ./api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
